### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by Sodki** [CyberShadow/metahumble#1]
Hi,

Can you provide a `requirements.txt` file so that we can easily run this?

Thanks!

**Comment by CyberShadow** [comment]
Hey, you found this!

I don't usually write Python but had a go at it:

https://github.com/CyberShadow/metahumble/commit/2f8d55ce02c775c4f1d98a4d5cf327c7bbd4c857

**Comment by Sodki** [comment]
Thanks! Still one library missing, I've added it on this PR: https://github.com/CyberShadow/metahumble/pull/2
