### ISSUE TITLE
Add missing LICENSE file

### ISSUE THREAD

**Issue by Sodki** [CyberShadow/metahumble#3]
The project is missing a LICENSE file, so we know what the licensing terms are.

**Comment by CyberShadow** [comment]
Thanks, added. I used the same license as the humblebundle library, MIT.

**Comment by CyberShadow** [comment]
BTW if you don't mind me asking, how did you find this project? I haven't announced it anywhere.

**Comment by Sodki** [comment]
Unfortunately you're depending on a GPL Python library, so your project needs to be GPL as well. I was looking into integrating https://github.com/metalink-dev/pymetalink instead because it's maintained, supports Metalink 4 and is MIT licensed.

I found your project via a Google search. :smile:

**Comment by CyberShadow** [comment]
D'oh. OK, switched to GPL then. Thanks for noticing.

I don't think the license _really_ matters, because the project is rather simple (just glue between two existing libraries) and is not likely to be redistributed often.

**Comment by Sodki** [comment]
I understand but, by default, without a license, we're breaking the law everytime we're downloading the project. :-(

Thanks for updating it!
